set_property SRC_FILE_INFO {cfile:c:/Users/japni/ibert_7series_gtp_0_ex/imports/example_ibert_7series_gtp_0.xdc rfile:../../../imports/example_ibert_7series_gtp_0.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U3 [get_ports SYSCLKP_I]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V3 [get_ports SYSCLKN_I]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y0 [get_cells u_ibert_core/inst/QUAD[0].u_q*/CH[0].u_ch/u_gtpe2_channel]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y1 [get_cells u_ibert_core/inst/QUAD[0].u_q*/CH[1].u_ch/u_gtpe2_channel]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y2 [get_cells u_ibert_core/inst/QUAD[0].u_q*/CH[2].u_ch/u_gtpe2_channel]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y3 [get_cells u_ibert_core/inst/QUAD[0].u_q*/CH[3].u_ch/u_gtpe2_channel]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_COMMON_X0Y0 [get_cells u_ibert_core/inst/QUAD[0].u_q*/u_common/u_gtpe2_common]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y24 [get_cells u_ibert_core/inst/QUAD[0].u_q*/u_common/u_clocking/local_txusr.u_txusr]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y25 [get_cells u_ibert_core/inst/QUAD[0].u_q*/u_common/u_clocking/rx_ind.u_rxusr0]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y26 [get_cells u_ibert_core/inst/QUAD[0].u_q*/u_common/u_clocking/rx_ind.u_rxusr1]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y27 [get_cells u_ibert_core/inst/QUAD[0].u_q*/u_common/u_clocking/rx_ind.u_rxusr2]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y28 [get_cells u_ibert_core/inst/QUAD[0].u_q*/u_common/u_clocking/rx_ind.u_rxusr3]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X0Y0 [get_cells u_buf_q0_clk0]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X0Y1 [get_cells u_buf_q0_clk1]
