# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Users/japni/ibert_7series_gtp_0_ex/imports/example_ibert_7series_gtp_0.xdc

# IP: ip/ibert_7series_gtp_0/ibert_7series_gtp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ibert_7series_gtp_0 || ORIG_REF_NAME==ibert_7series_gtp_0} -quiet] -quiet
